version: "3"
services:
  api:
    build: .
    depends_on:
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/sysprofile/
    command: uvicorn api.main:api --host 0.0.0.0 --port 8000 --reload
    environmnet:
